package com.orazaka.core.domain.model.chat;

import java.util.Map;

/**
 * Unified chat response record for all AI interactions.
 *
 * <p><b>{@link #tokenUsage()} is typed, not a metadata entry (ERR-127).</b> It is the number chat
 * is billed on, and it was previously visible only on {@link InternalChatResponse} — the type that
 * never leaves the engine. Every caller of the {@code AiClient} port therefore received a response
 * with no measurement at all, which is why {@code ChatGenerationStrategy} returned {@code
 * JobExecutionResult.of(result)} and every asynchronous chat step in a Studio run was billed
 * <b>nothing</b> (ADR-041). The synchronous path had it all along, through {@code
 * ChatCompletedEvent}; the asynchronous path had no way to reach it.
 *
 * @param content The text content generated by the AI model.
 * @param conversationId The session ID this response belongs to.
 * @param tokenUsage What this turn consumed. Never {@code null} — {@link TokenUsage#none()} says
 *     the provider reported nothing, which is a different fact from consuming nothing and is what
 *     makes an unmeasured turn release its hold rather than settle at a guess.
 * @param metadata Metadata associated with the response (e.g., provider name, duration).
 */
public record ChatResponse(
    String content, String conversationId, TokenUsage tokenUsage, Map<String, Object> metadata) {

  /** Compact canonical constructor enforcing the record's invariants (ERR-106). */
  public ChatResponse {
    tokenUsage = tokenUsage == null ? TokenUsage.none() : tokenUsage;
  }

  /**
   * A response carrying no token usage.
   *
   * <p>Convenience for the many callers — almost all of them tests — that construct a response
   * without caring what it consumed. It defaults to {@link TokenUsage#none()}, which says the
   * provider reported nothing, and an unmeasured turn releases its hold rather than being billed at
   * a guess. <b>Anything that actually measures must use the canonical constructor</b>: the one
   * production mapping, {@code ChatGeneratorClientImpl}, does.
   *
   * @param content the generated text
   * @param conversationId the session this belongs to
   * @param metadata the response metadata
   */
  public ChatResponse(String content, String conversationId, Map<String, Object> metadata) {
    this(content, conversationId, TokenUsage.none(), metadata);
  }

  /**
   * A response from a path that measures nothing.
   *
   * @param content the generated text
   * @param conversationId the session this belongs to
   * @param metadata the response metadata
   * @return the response, reporting no token usage
   */
  public static ChatResponse unmeasured(
      String content, String conversationId, Map<String, Object> metadata) {
    return new ChatResponse(content, conversationId, TokenUsage.none(), metadata);
  }
}
